- name: install pip packages
  pip:
    name:
    - ansible
    - beancount
    - deepdiff
    - fava
    - Flask
    - ipython
    - jupyter
    - matplotlib
    - numpy
    - oauth2
    - pandas
    - pip
    - pms5003
    - prometheus-client
    - pytest
    - pyyaml
    - requests
    - sense-hat
    - simplejson
    - wheel
    state: latest
